### ISSUE TITLE
Mail notifications not received when creating an agreement

### ISSUE THREAD

**Issue by bgrossiordLs** [adobe-sign/AdobeSignJavaSdk#14]
Hello,

I'm working on the integration of adobe sign for one of my client. I am using the latest version of the sdk.

I succeeded in creating a transientDocument and the related agreement (with draft status/state) that seems ok for me but I'm not receiving any e-mail.

When I'm comparing this agreement with one generated using the dashboard (that's sending me the notification e-mail) I don't see much difference except for the status that is OUT_FOR_SIGNATURE and not DRAFT. You can take a look at the one I created: [agreement.txt](https://github.com/adobe-sign/AdobeSignJavaSdk/files/2745951/agreement.txt)

In addition when I'm setting the status of my AgreementInfo to OUT_FOR_SIGNATURE and it's State to DRAFT (because there is no state corresponding to out for signature) it seems to have no impact on the final status (it stays on DRAFT).

Maybe I'm misunderstanding something, can someone clarify it please?

**Comment by adobesignsdk** [comment]
@bgrossiordLs When an agreement is created in a draft **state**, the agreement has still not been sent to the recipients and the sender has an option to revisit the draft created before finally sending it out.

The _status_ of the created agreement is decided based on the enum(DRAFT, IN_PROCESS) passed in **state** field of the agreement creation request body. If you want to directly send out an agreement without creating a draft first, you need to set the state to IN_PROCESS in the request. 

The OUT_FOR_SIGNATURE is the _status_ that the agreement will land if the participant has SIGNER role. This status is provided in the response of the GET /agreements/id API. Please refer to our [swagger documentation page](https://secure.na1.echosign.com/public/docs/restapi/v6#!/agreements/createAgreement) for more details on draft.

**Comment by bgrossiordLs** [comment]
@adobesignsdk That's clear. Thanks a lot for answering so quickly
