### ISSUE TITLE
Request must be made to correct API access point

### ISSUE THREAD

**Issue by cmcornejocrespo** [adobe-sign/AdobeSignJavaSdk#4]
Hi there,

I've checkout the latest tag, followed the instructions and updated the config.properties accordingly.
I'm getting a recurrent error while trying to run the tests.
It retrieves successfully the baseUrl based on the accessToken but I'm getting some tests throwing this exception:

`com.adobe.sign.utils.ApiException: Request must be made to correct API access point (e.g. use GET /base_uris).`

I'm guessing that I'm missing setting up the API access point, but I can't find where to set this value.

Any tips??

Regards,
Carlos M.

**Comment by adobesignsdk** [comment]
Hi Carlos,

Can you please confirm if you have modified the envHostName parameter in the config.properties? If yes, I will request you to share the value that is assigned to the envHostName parameter.

**Comment by cmcornejocrespo** [comment]
Hi Folks,

sorry about the late rresponse. My bad as I should have replied ages ago. All good on my side.

Please consider closing the issue as I was not configuring properly the config file.
